{
 "title": "Orbit Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Connected Clients",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "Connected_Clients" }
   ]
  },
  {
   "title": "Messages (5 minutes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(Message_Sizes_count[1m])" }
   ]
  },
  {
   "title": "Addressables",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "Addressable_Count" }
   ]
  },
  {
   "title": "Messages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(Message_Sizes_count[10s])" }
   ]
  },
  {
   "title": "Retries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(Retry_Attempts_total[10s])"
    },
    { "expr": "Retry_Errors_total" }
   ]
  }
 ]
}