apiVersion: apps/v1
kind: Deployment
metadata:
  name: orbit-carnival
  labels:
    app: orbit-carnival
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orbit-carnival
  template:
    metadata:
      labels:
        app: orbit-carnival
    spec:
      containers:
        - name: orbit-carnival
          image: orbit-carnival
          ports:
          - name: http
            containerPort: 8001
          env:
          - name: ORBIT_URL
            value: "dns:///orbit-test-server:50056/"
---
apiVersion: v1
kind: Service
metadata:
  name: orbit-carnival
  labels:
    app: orbit-carnival
spec:
  selector:
    app: orbit-carnival
  ports:
  - name: http
    port: 8001
  - name: debug
    port: 5005
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: orbit-carnival-ingress
  labels:
    app: orbit-carnival
spec:
  backend:
    serviceName: orbit-carnival
    servicePort: 8001