apiVersion: skaffold/v2beta2
kind: Config
metadata:
  name: orbit-carnival
build:
  artifacts:
  - image: orbit-carnival
    context: .
    docker:
      dockerfile: docker/Dockerfile
deploy:
  helm:
    releases:
    - name: orbit-carnival
      chartPath: charts/orbit-carnival
      skipBuildDependencies: true
      setValues:
        url: orbit-carnival
        orbit.enabled: true
      values:
        image: orbit-carnival
