# Default values for charts.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

image: "orbitframework/orbit-sample"
orbitUrl: "dns:///orbit:50056/"

resources: {}

meters:
  enabled: true

orbit:
  enabled: true
  url: localhost
  fullnameOverride: "orbit"
  node:
    replicas: 1
    containerPort: 50056
    service:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9090'
  addressableDirectory:
    replicas: 1
  nodeDirectory:
    replicas: 1
