# Default values for charts.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

image: ""
orbitUrl: "dns:///orbit:50056/"

resources: {}

orbit:
  enabled: true
  url: localhost
  fullnameOverride: "orbit"
  node:
    replicas: 1
    containerPort: 50056
  addressableDirectory:
    replicas: 1
  nodeDirectory:
    replicas: 1
